NAME=GoogleAnalytics
VERSION=3.13.0

COMPONENTS_BUILD_CACHE_PATH ?= $(HOME)/Library/Caches/Components
COMPONENTS_INSTALL_PATH ?= ./Components

COMPONENT_BUILD_PATH=$(COMPONENTS_BUILD_CACHE_PATH)/$(NAME)
COMPONENT_TARBALL_PATH=$(COMPONENT_BUILD_PATH)/$(NAME)-$(VERSION).tar.gz
COMPONENT_SOURCE_PATH=$(COMPONENT_BUILD_PATH)/$(NAME)-$(VERSION)
COMPONENT_FRAMEWORK_PATH=$(COMPONENT_SOURCE_PATH)/Frameworks/$(NAME).framework

COMPONENT_INSTALL_PATH=$(COMPONENTS_INSTALL_PATH)/$(NAME)/

### URLs

HASH=9b1bb5e186325dc2
COMPONENT_TARBALL_URL=https://www.gstatic.com/cpdc/$(HASH)-$(NAME)-${VERSION}.tar.gz

### Targets

.PHONY: install update uninstall clean prepare purge

install: $(COMPONENT_INSTALL_PATH)

uninstall:
	rm -rf $(COMPONENT_INSTALL_PATH)

update: uninstall install

clean:
	rm -rf $(COMPONENT_SOURCE_PATH)
	rm -rf $(COMPONENT_TARBALL_PATH)

purge: uninstall clean

### Artefacts

$(COMPONENT_INSTALL_PATH): $(COMPONENT_SOURCE_PATH)
	mkdir $(COMPONENT_INSTALL_PATH)
	cp -R $(COMPONENT_SOURCE_PATH)/Headers $(COMPONENT_INSTALL_PATH)
	cp -R $(COMPONENT_SOURCE_PATH)/Libraries $(COMPONENT_INSTALL_PATH)

$(COMPONENT_SOURCE_PATH): $(COMPONENT_TARBALL_PATH)
	mkdir -p $(COMPONENT_SOURCE_PATH)
	tar xzf $(COMPONENT_TARBALL_PATH) --directory ${COMPONENT_SOURCE_PATH}

	# Un-tar touches $(COMPONENT_BUILD_PATH)
	# so we must touch tarball and then source path to restore logical order
	touch $(COMPONENT_TARBALL_PATH)
	touch $(COMPONENT_SOURCE_PATH)

$(COMPONENT_TARBALL_PATH): $(COMPONENT_BUILD_PATH)
	wget --no-use-server-timestamps $(COMPONENT_TARBALL_URL) -O $(COMPONENT_TARBALL_PATH)

$(COMPONENT_BUILD_PATH):
	mkdir -p $(COMPONENT_BUILD_PATH)

